# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_events', '0026_auto_20180112_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlistplugin',
            name='style',
            field=models.CharField(choices=[('standard', 'Standard'), ('bootstrap_carousel', 'Bootstrap_Carousel'), ('bootstrap_carousel_thumbnails', 'Bootstrap_Carousel_Thumbnails')], default='standard', max_length=50, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='eventsconfigtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_events.EventsConfig'),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_events.Event'),
        ),
        migrations.AlterField(
            model_name='upcomingpluginitem',
            name='style',
            field=models.CharField(choices=[('standard', 'Standard'), ('bootstrap_carousel', 'Bootstrap_Carousel'), ('bootstrap_carousel_thumbnails', 'Bootstrap_Carousel_Thumbnails')], default='standard', max_length=50, verbose_name='Style'),
        ),
    ]
